---
abstract: 'JavaScript WebUI for PlugAuth'
author:
  - 'Graham Ollis <gollis@sesda2.com>'
build_requires:
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  File::ShareDir::Install: 0.03
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PlugAuth-WebUI
requires:
  File::ShareDir: 0
  Path::Class::Dir: 0
  Path::Class::File: 0
  perl: v5.10.0
  strict: 0
  warnings: 0
version: 0.01
