---
abstract: 'JavaScript WebUI for PlugAuth'
author:
  - 'Graham Ollis <graham.a.ollis@nasa.gov>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  File::ShareDir::Install: 0.03
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300021, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PlugAuth-WebUI
requires:
  File::Copy: 0
  File::ShareDir: 0
  Getopt::Long: 0
  Path::Class: 0
  Path::Class::Dir: 0
  Path::Class::File: 0
  perl: v5.10.0
version: 0.10
